// General
const LOADING_START_BOOKING = "LOADING_START_BOOKING";
const LOADING_END_BOOKING = "LOADING_END_BOOKING";
const LOADING_START_SIGNUP = "LOADING_START_SIGNUP";
const LOADING_END_SIGNUP = "LOADING_END_SIGNUP";
const LOADING_START_SIDEMENU = "LOADING_START_SIDEMENU";
const LOADING_END_SIDEMENU = "LOADING_END_SIDEMENU";
const LOADING_START_DASHBOARD = "LOADING_START_DASHBOARD";
const LOADING_END_DASHBOARD = "LOADING_END_DASHBOARD";
const LOADING_START_CLASS_SCHEDULE = "LOADING_START_CLASS_SCHEDULE";
const LOADING_END_CLASS_SCHEDULE = "LOADING_END_CLASS_SCHEDULE";
const LOADING_START_ASSIGNED_WORKOUT = "LOADING_START_ASSIGNED_WORKOUT";
const LOADING_END_ASSIGNED_WORKOUT = "LOADING_END_ASSIGNED_WORKOUT";
const LOADING_START_WORKOUT = "LOADING_START_WORKOUT";
const LOADING_END_WORKOUT = "LOADING_END_WORKOUT";

const LOADING_START_MEMBER = "LOADING_START_MEMBER";
const LOADING_END_MEMBER = "LOADING_END_MEMBER";

//Auth - login / Register
const MEMBERSHIP_DROPDOWN_LIST = "MEMBERSHIP_DROPDOWN_LIST";
const MEMBERSHIP_CLASS_LIST = "MEMBERSHIP_CLASS_LIST";
const MEMBERSHIP_DAYS = "MEMBERSHIP_DAYS";
const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
const GET_USER_DETAILS = "GET_USER_DETAILS";
const USER_LOGOUT = "USER_LOGOUT";

//Sidebar Menu
const SET_ACCESSRIGHT = "SET_ACCESSRIGHT";
const SET_STAFF_ACCESSRIGHT = "SET_STAFF_ACCESSRIGHT";

//Dashboard
const WEIGHT_DATA = "WEIGHT_DATA";
const WAIST_DATA = "WAIST_DATA";
const THIGH_DATA = "THIGH_DATA";
const ARMS_DATA = "ARMS_DATA";
const HEIGHT_DATA = "HEIGHT_DATA";
const CHEST_DATA = "CHEST_DATA";
const FAT_DATA = "FAT_DATA";

//Class Booking types
const BOOKING_LIST = "BOOKING_LIST";
const ADD_BOOKING = "ADD_BOOKING";
const CANCEL_BOOKING = "CANCEL_BOOKING";
const GET_CLASS_SCHEDULE = "GET_CLASS_SCHEDULE";

const LOADING_START = "LOADING_START";
const LOADING_END = "LOADING_END";

//Staff Member types
const STAFFMEMBER_LIST = "STAFFMEMBER_LIST";
const LOADING_START_STAFF = "LOADING_START_STAFF";
const LOADING_END_STAFF = "LOADING_END_STAFF";

//MemberShip List Types
const MEMBERSHIP_LIST = "MEMBERSHIP_LIST";
const LOADING_START_MEMBERSHIP_TYPE = "LOADING_START_MEMBERSHIP_TYPE";
const LOADING_END_MEMBERSHIP_TYPE = "LOADING_END_MEMBERSHIP_TYPE";

//Group List Types
const GROUP_LIST = "GROUP_LIST";
const LOADING_START_GROUP_TYPE = "LOADING_START_GROUP_TYPE";
const LOADING_END_GROUP_TYPE = "LOADING_END_GROUP_TYPE";

//Activity List Types
const ACTIVITY_LIST = "ACTIVITY_LIST";
const LOADING_START_ACTIVITY = "LOADING_START_ACTIVITY";
const LOADING_END_ACTIVITY = "LOADING_END_ACTIVITY";

//Fees Payment Types
const FEES_PAYMENT_LIST = "FEES_PAYMENT_LIST";
const LOADING_START_FEESPAYMENT = "LOADING_START_FEESPAYMENT";
const LOADING_END_FEESPAYMENT = "LOADING_END_FEESPAYMENT";
const PAYMENT_INVOICE = "PAYMENT_INVOICE";
const INVOICE_SEND = "INVOICE_SEND";

//Notice Types
const NOTICE_LIST = "NOTICE_LIST";
const LOADING_START_NOTICE = "LOADING_START_NOTICE";
const LOADING_END_NOTICE = "LOADING_END_NOTICE";

//Measurement Types
const ADD_MEASUREMENT = "ADD_MEASUREMENT";
const MEASUREMENT_LIST = "MEASUREMENT_LIST";
const LOADING_START_MEASUREMENT = "LOADING_START_MEASUREMENT";
const LOADING_END_MEASUREMENT = "LOADING_END_MEASUREMENT";

//Nutrition Schedule Types
const NUTRITION_LIST = "NUTRITION_LIST";
const PRODUCTGROUP_LIST = "PRODUCTGROUP_LIST";
const LOADING_START_NUTRITION = "LOADING_START_NUTRITION";
const LOADING_END_NUTRITION = "LOADING_END_NUTRITION";

// HISTORY 
const HISTORY_LIST = "HISTORY_LIST";
// Product
const PRODUCT_LIST = "PRODUCT_LIST";
// My home
const MY_HOME = "MY_HOME";

//Subscription schedule Types
const SUBSCRIPTION_LIST = "SUBSCRIPTION_LIST";
const LOADING_START_SUBSCRIPTION = "LOADING_START_SUBSCRIPTION";
const LOADING_END_SUBSCRIPTION = "LOADING_END_SUBSCRIPTION";

//Message Types
const INBOX_MESSAGE_LIST = "INBOX_MESSAGE_LIST";
const LOADING_START_INBOX_MESSAGE = "LOADING_START_INBOX_MESSAGE";
const LOADING_END_INBOX_MESSAGE = "LOADING_END_INBOX_MESSAGE";
const LOADING_START_MESSAGE = "LOADING_START_MESSAGE";
const LOADING_END_MESSAGE = "LOADING_END_MESSAGE";
const INBOX_VIEW_MESSAGE_LIST = "INBOX_VIEW_MESSAGE_LIST";
const SENT_MESSAGE_LIST = "SENT_MESSAGE_LIST";
const MEMBER_AND_STAFF_LIST = "MEMBER_AND_STAFF_LIST";
const SENT_VIEW_MESSAGE_LIST = "SENT_VIEW_MESSAGE_LIST";

//Message Types
const MEMBER_CLASS_LIST = "MEMBER_CLASS_LIST";
const LOADING_START_ATTENDANCE = "LOADING_START_ATTENDANCE";
const LOADING_END_ATTENDANCE = "LOADING_END_ATTENDANCE";
const MEMBER_DATA_LIST = "MEMBER_DATA_LIST";

//Staff Dashboard Types
const LOADING_START_STAFF_DASHBOARD = "LOADING_START_STAFF_DASHBOARD";
const LOADING_END_STAFF_DASHBOARD = "LOADING_END_STAFF_DASHBOARD";
const STAFF_ACTIVITY_LIST = "STAFF_ACTIVITY_LIST";
const STAFF_GROUP_LIST = "STAFF_GROUP_LIST";
const STAFF_MEMBERSHIP_LIST = "STAFF_MEMBERSHIP_LIST";
const STAFF_RESERVATION_LIST = "STAFF_RESERVATION_LIST";
const STAFF_CLASS_LIST = "STAFF_CLASS_LIST";

//Class Schedule Types
const CLASS_SCHEDULE_LIST = "CLASS_SCHEDULE_LIST";
const CLASS_LIST = "CLASS_LIST";

//Assigned Workout Types
const ASSIGNED_WORKOUT_LIST = "ASSIGNED_WORKOUT_LIST";
const WORKOUT_DATA = "WORKOUT_DATA";

//Workout Types
const WORKOUT_DATES_LIST = "WORKOUT_DATES_LIST";
const WORKOUT_DETAILS = "WORKOUT_DETAILS";
const MAKE_WORKOUT_EMPTY = "MAKE_WORKOUT_EMPTY";
const PREVIEW_WORKOUT = "PREVIEW_WORKOUT";
const MAKE_PREVIEW_WORKOUT_EMPTY = "MAKE_PREVIEW_WORKOUT_EMPTY";

//Staff Member Report Types
const LOADING_START_REPORT_DASHBOARD = "LOADING_START_REPORT_DASHBOARD";
const LOADING_END_REPORT_DASHBOARD = "LOADING_END_REPORT_DASHBOARD";
const MEMBER_ATTENDANCE_REPORT = "MEMBER_ATTENDANCE_REPORT";
const STAFF_ATTENDANCE_REPORT = "STAFF_ATTENDANCE_REPORT";
const FESS_PAYMENT_REPORT = "FESS_PAYMENT_REPORT";
const INCOME_PAYMENT_REPORT = "INCOME_PAYMENT_REPORT";
const SELL_PRODUCT_REPORT = "SELL_PRODUCT_REPORT";
const MEMBERSHIP_REPORT = "MEMBERSHIP_REPORT";

//Staff Member Report Types
const ALL_CLASS_LIST = "ALL_CLASS_LIST";
const ATTENDANCE_DATA = "ATTENDANCE_DATA";

const SHOW_ERROR = "SHOW_ERROR";

export {
  LOADING_START_BOOKING,
  LOADING_END_BOOKING,
  LOADING_START_SIGNUP,
  LOADING_END_SIGNUP,
  MEMBERSHIP_DROPDOWN_LIST,
  MEMBERSHIP_CLASS_LIST,
  MEMBERSHIP_DAYS,
  SIGNUP_SUCCESS,
  LOADING_START_SIDEMENU,
  LOADING_END_SIDEMENU,
  SET_ACCESSRIGHT,
  SET_STAFF_ACCESSRIGHT,
  LOADING_START_DASHBOARD,
  LOADING_END_DASHBOARD,
  WEIGHT_DATA,
  WAIST_DATA,
  THIGH_DATA,
  ARMS_DATA,
  HEIGHT_DATA,
  CHEST_DATA,
  FAT_DATA,
  BOOKING_LIST,
  ADD_BOOKING,
  CANCEL_BOOKING,
  GET_CLASS_SCHEDULE,
  NUTRITION_LIST,
  LOADING_START_NUTRITION,
  LOADING_END_NUTRITION,
  MEASUREMENT_LIST,
  ADD_MEASUREMENT,
  LOADING_START_MEASUREMENT,
  LOADING_END_MEASUREMENT,
  NOTICE_LIST,
  LOADING_START_NOTICE,
  LOADING_END_NOTICE,
  INVOICE_SEND,
  PAYMENT_INVOICE,
  FEES_PAYMENT_LIST,
  LOADING_START_FEESPAYMENT,
  LOADING_END_FEESPAYMENT,
  ACTIVITY_LIST,
  LOADING_START_ACTIVITY,
  LOADING_END_ACTIVITY,
  GROUP_LIST,
  LOADING_START_GROUP_TYPE,
  LOADING_END_GROUP_TYPE,
  LOADING_START_MEMBERSHIP_TYPE,
  LOADING_END_MEMBERSHIP_TYPE,
  LOADING_START_STAFF,
  LOADING_END_STAFF,
  LOADING_START,
  LOADING_END,
  SHOW_ERROR,
  STAFFMEMBER_LIST,
  MEMBERSHIP_LIST,
  SUBSCRIPTION_LIST,
  LOADING_START_SUBSCRIPTION,
  LOADING_END_SUBSCRIPTION,
  INBOX_MESSAGE_LIST,
  LOADING_START_MESSAGE,
  LOADING_END_MESSAGE,
  LOADING_START_INBOX_MESSAGE,
  LOADING_END_INBOX_MESSAGE,
  INBOX_VIEW_MESSAGE_LIST,
  SENT_MESSAGE_LIST,
  MEMBER_AND_STAFF_LIST,
  SENT_VIEW_MESSAGE_LIST,
  MEMBER_CLASS_LIST,
  LOADING_START_ATTENDANCE,
  LOADING_END_ATTENDANCE,
  MEMBER_DATA_LIST,
  LOADING_START_STAFF_DASHBOARD,
  LOADING_END_STAFF_DASHBOARD,
  STAFF_ACTIVITY_LIST,
  STAFF_GROUP_LIST,
  STAFF_MEMBERSHIP_LIST,
  STAFF_RESERVATION_LIST,
  STAFF_CLASS_LIST,
  LOADING_START_CLASS_SCHEDULE,
  LOADING_END_CLASS_SCHEDULE,
  CLASS_SCHEDULE_LIST,
  CLASS_LIST,
  LOADING_START_ASSIGNED_WORKOUT,
  LOADING_END_ASSIGNED_WORKOUT,
  ASSIGNED_WORKOUT_LIST,
  WORKOUT_DATA,
  LOADING_START_REPORT_DASHBOARD,
  LOADING_END_REPORT_DASHBOARD,
  MEMBER_ATTENDANCE_REPORT,
  STAFF_ATTENDANCE_REPORT,
  FESS_PAYMENT_REPORT,
  INCOME_PAYMENT_REPORT,
  SELL_PRODUCT_REPORT,
  MEMBERSHIP_REPORT,
  LOADING_START_WORKOUT,
  LOADING_END_WORKOUT,
  WORKOUT_DATES_LIST,
  WORKOUT_DETAILS,
  MAKE_WORKOUT_EMPTY,
  PREVIEW_WORKOUT,
  MAKE_PREVIEW_WORKOUT_EMPTY,
  GET_USER_DETAILS,
  LOADING_START_MEMBER,
  LOADING_END_MEMBER,
  ALL_CLASS_LIST,
  ATTENDANCE_DATA,
  USER_LOGOUT,
  HISTORY_LIST,
  PRODUCTGROUP_LIST,
  PRODUCT_LIST,
  MY_HOME
};
